### ISSUE TITLE
rxjs operators

### ISSUE THREAD

**Issue by ovidius72** [njl07/rx-http-request#10]
Is it possible to use operators such as map, flatMap, debounce and so on.. ?
I've tried importing them with `import 'rxjs/add/operator/map'` but it doesn't work. I get .".map is not defined."

**Comment by njl07** [comment]
@ovidius72 thanks for your question and all works fine with all `rxjs` operators.

This example can help you:

```javascript
import { RxHR } from '@akanass/rx-http-request';
import 'rxjs/add/operator/mergeMap';

RxHR.get('http://www.google.fr').flatMap(_ => {
    console.log('Google crawled but I\'m lost');
    return RxHR.get('http://perdu.com');
}).subscribe(
    (data) => {
        if (data.response.statusCode === 200) {
            console.log(data.body); // Show the HTML for perdu.com homepage.
        }
    },
    (err) => console.error(err)
);
```

Thanks again to use this library.

**Comment by ovidius72** [comment]
Thank you for your quick support, however I cannot get it working. I'm using CommonJS syntax.
```
const RxHR = require('@akanass/rx-http-request').RxHR;
```
then 

```
require('rxjs/add/operator/mergeMap');
```
OR
```
import 'rxjs/add/operator/mergeMap';
```

But even using the same example you posted below I always get 
> ....get(...).flatMap is not a function

Maybe I'm doing something wrong. Or maybe I should upgrade node (now I0m using 6.10.0).  I'll check it out better later .
Thank you.

**Comment by njl07** [comment]
I tested with `CommonJS` too and all works fine for me.

Can you create a `gist` file with all your example and I'll test it to show what's happen

**Comment by xabitrigo** [comment]
I had a very similar problem and it was due to having a different rxjs version declared as a dependency. My dependency was `^5.3.0` while the package's one was `^5.4.0`.

It took a while to find the problem, so I got curious and searched for a possible solution, and I want to leave this message as a suggestion: It might be nice to have a peer dependency declared on your package.json for the `^5.4.0` version so this problem is raised when installing the package instead of being raised at runtime

**Comment by njl07** [comment]
@xabitrigo we have a dependency for `^5.4.0` so this version is always installed and I haven't problem with operators.

Give me `gist` about your problem to test it.

**Comment by xabitrigo** [comment]
Yes, that's what I meant. I was using two different kind of Observables:

- The epics from redux-observable expected `^5.3.0` version of rxjs. That's what I had on my packages.json
- The returned object from RxHR.get() was version `^5.4.0`. That's what rx-http-request depended on.

The node_modules directory structure was something like this:

```
node_modules/
    rxjs/ <-- v 5.3.0
    @akanass/
        rx-http-request/
            node_modules/
                rxjs/ <-- v 5.4.0
```

Apparently they are not fully compatible between them. I say apparently because once I upgraded my own dependency to `^5.4.0` the problem seemed to disappear (thus my suggestion of a peer-dependency). And I say "seemed" because it only disappeared on the testing environment, but on the browser it resurfaced. So I no longer think it's a versioning problem.

What I am trying to do is to call an API from both the browser environment and the node testing environment. Observable.ajax() doesn't seem to work because it depends on XMLHttpRequest which is only available on browsers, so I found this library. I then intend to mock the request with nock or something similar if I'm on the testing environment.

I can try making a gist, but I don't think it will be of use, because my problem happens depending on the environment.

This is my api call. It's correctly subscribed to later by the redux-observable epic middleware.

```
export const getTeams = () => {
  let options = { json: true };
  let a = RxHR.get(API_BASE_URL + '/teams', options);
  let b = a.map(
    (data) => {
      if (data.response.statusCode === 200){
        return data.body;
      }
    }
  )
  return b;
}
```

The epic is like this:
```
export const fetchTeamsEpic = action$ =>
  action$.ofType(FETCH_TEAM_REQUEST)
    .mergeMap($action =>
      getTeams()
        .map(response => fetchTeamsSuccess(response))
    );
```

This code now works in the testing environment, but on the browser it shows an error:
```
Uncaught TypeError: a.map is not a function
  at getTeams ....
```

----

If I try to pass the RxHR object outside getTeams, returning directly `a`:

```
export const getTeams = () => {
  let options = { json: true };
  let a = RxHR.get(API_BASE_URL + '/teams', options);
  return a;
}
```

The error I get is the following:

```
Uncaught TypeError: (0, _merchandisePosApi.getTeams)(...).map is not a function
  at MergeMapSubscriber.project ...
```

Which is at the epic:

```
export const fetchTeamsEpic = action$ =>
  action$.ofType(FETCH_TEAM_REQUEST)
    .mergeMap($action =>
      getTeams()
        .map(response => fetchTeamsSuccess(response)) // <--The error is in this map
    );
```

Yesterday, before I updated rxjs to `5.4.0` this was happening backwards: the browser worked and the tests didn't.

Any suggestions?

I am about to give up on this. Not being able to test is a deal killer (it's one of the main points of this project)

**Comment by njl07** [comment]
Have you imported `Observable` and `map` operator in your epic code ?

```javascript
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';
```

`map` function is an additional operator of `Observable`.

Your function `getTeams()` returns an `Observable` so you must to add the operator to it.

**Comment by xabitrigo** [comment]
I am importing 'rxjs' at my entry javascript file, as stated in https://redux-observable.js.org/docs/Troubleshooting.html.

**Comment by njl07** [comment]
I think it's not the good way to import all in your code.

And operator must be imported where you call it

**Comment by xabitrigo** [comment]
I've tried both ways, the error is the same. Also, if I wrap my call inside an Observable.of like this:

```
export const getTeams = () => {
  let options = { json: true };
  let a = Observable.of(RxHR.get(API_BASE_URL + '/teams', options));
  let b = a.map(
    (data) => {
      if (data.response.statusCode === 200){
        return data.body;
      }
    }
  )
  return b;
}
```

the error is gone. It doesn't work as expected because I don't have the values I want, but it doesn't crash. 

I've been looking inside browser.js (there is a warning on the console about it being a pre-built javascript file), maybe it has something to do with it?

**Comment by njl07** [comment]
I'm sorry but I think the problem is from your `redux` library because if I test directly in the browser, I haven't problem.

**Comment by xabitrigo** [comment]
It's ok. I'll dig a bit further and if I find the problem (or the solution) I'll report it here. Thanks.
