### ISSUE TITLE
How to use retry operator

### ISSUE THREAD

**Issue by acid122** [njl07/rx-http-request#31]
Hi guys, first, I want to say this library really helps lot when I want to use rxjs in node; thanks to the authors. I found a problem about how to use retry, the following demo code seems not to work(the api is a folk one, just causes network errors): 

const apiData = RxHR.get('/api/data').pipe(

    map(res => {
        console.log(res);
        if (!res.response) {
            throw 'Value expected!';
        }
        return res.response;
    }),
    retry(2),
    catchError((err, caught) => {
        console.log(`catchError`);
    }
    )
);

apiData.subscribe({
    next(x) { console.log('data: ', x); },
    error(err) { console.log('errors', err); }
});

**Comment by akanass** [comment]
The `retry` operator can only be used if `observable ` isn’t completed but when you do a `http request` each time `complete` is done so you can’t do it.

`retry` can be performed with `websocket` because connection still be opened but in `http` connection is closed each time and you have to do a new request.

The original `request` library used can’t perform a retry so you can’t do it with this library which is a `rxjs` wrapper of it.
